// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案默认后跑 pnpm gen:archetype-defaults）。
// 档案参数默认值桥接：headless/MCP 生成缺参时 runtime 按 (archetypeId, taskKind) 兜底填，既有值优先。
export const ARCHETYPE_WIRE_DEFAULTS: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  "seedance-2": {
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "aspect_ratio": "16:9",
        "duration": 5,
        "generate_audio": true,
        "model": "bytedance/seedance-2"
      }
    }
  },
  "happyhorse": {
    "text_to_video": {
      "*": {
        "resolution": "1080p",
        "audio_setting": "auto",
        "model": "happyhorse/video-edit"
      }
    }
  },
  "gpt-image-2": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "auto",
        "resolution": "1K",
        "model": "gpt-image-2-text-to-image"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "auto",
        "resolution": "1K",
        "model": "gpt-image-2-image-to-image"
      }
    }
  },
  "seedream": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "model": "seedream/4.5-text-to-image"
      },
      "apimart": {
        "size": "1:1",
        "resolution": "2K",
        "model": "seedream/4.5-text-to-image"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "1:1",
        "quality": "basic",
        "model": "seedream/4.5-edit"
      },
      "apimart": {
        "size": "1:1",
        "resolution": "2K",
        "model": "seedream/4.5-edit"
      }
    }
  },
  "nano-banana": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "output_format": "png",
        "model": "google/nano-banana"
      },
      "apimart": {
        "size": "1:1",
        "model": "google/nano-banana"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "1:1",
        "output_format": "png",
        "model": "google/nano-banana-edit"
      },
      "apimart": {
        "size": "1:1",
        "model": "google/nano-banana-edit"
      }
    }
  },
  "kling-3.0": {
    "text_to_video": {
      "*": {
        "mode": "pro",
        "duration": "5",
        "aspect_ratio": "16:9",
        "sound": false,
        "model": "kling-3.0/video"
      },
      "apimart": {
        "mode": "pro",
        "duration": 5,
        "aspect_ratio": "16:9",
        "audio": false,
        "model": "kling-3.0/video"
      }
    },
    "image_to_video": {
      "*": {
        "mode": "pro",
        "duration": "5",
        "aspect_ratio": "16:9",
        "sound": false,
        "model": "kling-3.0/video"
      },
      "apimart": {
        "mode": "pro",
        "duration": 5,
        "aspect_ratio": "16:9",
        "audio": false,
        "model": "kling-3.0/video"
      }
    }
  },
  "qwen-image": {
    "text_to_image": {
      "*": {
        "size": "1:1",
        "resolution": "1K",
        "model": "qwen-image-2.0"
      }
    },
    "image_edit": {
      "*": {
        "size": "1:1",
        "resolution": "1K",
        "model": "qwen-image-2.0"
      }
    }
  },
  "imagen-4": {
    "text_to_image": {
      "*": {
        "size": "16:9"
      }
    }
  },
  "z-image-turbo": {
    "text_to_image": {
      "*": {
        "size": "1:1",
        "resolution": "1K"
      }
    }
  },
  "sora-2": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 4,
        "model": "sora-2"
      }
    },
    "image_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 4,
        "model": "sora-2"
      }
    }
  },
  "veo-3.1": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "model": "veo3.1-fast"
      }
    },
    "image_to_video": {
      "*": {
        "generation_type": "frame",
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "model": "veo3.1-fast"
      }
    }
  },
  "wan-2.7": {
    "text_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "1080P",
        "duration": 5
      }
    },
    "image_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "1080P",
        "duration": 5
      }
    }
  },
  "hailuo-2.3": {
    "text_to_video": {
      "*": {
        "resolution": "768p",
        "duration": 6,
        "model": "MiniMax-Hailuo-2.3"
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "768p",
        "duration": 6,
        "model": "MiniMax-Hailuo-2.3"
      }
    }
  },
  "seedance-2-apimart": {
    "text_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2.0"
      }
    },
    "image_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2.0"
      }
    }
  },
  "omni-flash-ext": {
    "text_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "720p",
        "duration": 6
      }
    },
    "image_to_video": {
      "*": {
        "generation_type": "reference",
        "size": "16:9",
        "resolution": "720p",
        "duration": 6
      }
    }
  },
  "nomi-audio": {
    "text_to_audio": {
      "*": {
        "voice": "alloy",
        "speed": 1,
        "model": "gpt-4o-mini-tts"
      }
    },
    "transcribe": {
      "*": {
        "language": "",
        "model": "whisper-1"
      }
    }
  },
  "volcengine-doubao-tts": {
    "text_to_audio": {
      "*": {
        "voice": "zh_female_vv_uranus_bigtts"
      }
    }
  },
  "seed-tts": {
    "text_to_audio": {
      "*": {
        "voice": "zh_female_vv_uranus_bigtts"
      }
    }
  },
  "modelscope-image": {
    "text_to_image": {
      "*": {
        "size": "1024x1024"
      }
    }
  },
  "volcengine-seedream": {
    "text_to_image": {
      "*": {
        "size": "2048x2048"
      }
    }
  },
  "volcengine-seedance-2": {
    "text_to_video": {
      "*": {
        "ratio": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2-0-260128"
      }
    },
    "image_to_video": {
      "*": {
        "ratio": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2-0-260128"
      }
    }
  },
  "dreamina-seedance-2": {
    "text_to_video": {
      "*": {
        "dreamina_cmd": "text2video",
        "ratio": "16:9",
        "video_resolution": "720p",
        "duration": 5,
        "model": "seedance2.0fast"
      }
    },
    "image_to_video": {
      "*": {
        "dreamina_cmd": "multimodal2video",
        "ratio": "16:9",
        "video_resolution": "720p",
        "duration": 5,
        "model": "seedance2.0fast"
      }
    }
  },
  "dreamina-image": {
    "text_to_image": {
      "*": {
        "ratio": "1:1",
        "resolution_type": "2k",
        "model": "5.0"
      }
    },
    "image_edit": {
      "*": {
        "ratio": "1:1",
        "resolution_type": "2k",
        "model": "5.0"
      }
    }
  },
  "dreamina-upscale": {
    "image_edit": {
      "*": {
        "resolution_type": "2k"
      }
    }
  },
  "dreamina-multiframe": {
    "image_to_video": {
      "*": {
        "duration": 3
      }
    }
  },
  "hunyuan3d": {
    "text_to_3d": {
      "*": {
        "generateType": "Normal",
        "faceCount": 500000,
        "enablePbr": true
      }
    },
    "image_to_3d": {
      "*": {
        "generateType": "Normal",
        "faceCount": 500000,
        "enablePbr": true
      }
    }
  },
  "hitem3d": {
    "image_to_3d": {
      "*": {
        "requestType": "mesh",
        "resolution": "1536pro",
        "face": 2000000
      }
    }
  },
  "meshy6": {
    "text_to_3d": {
      "*": {
        "artStyle": "realistic",
        "topology": "triangle",
        "targetPolycount": 30000,
        "symmetryMode": "auto",
        "shouldRemesh": true,
        "enablePbr": true
      }
    },
    "image_to_3d": {
      "*": {
        "topology": "triangle",
        "targetPolycount": 30000,
        "symmetryMode": "auto",
        "shouldRemesh": true,
        "shouldTexture": true,
        "enablePbr": true
      }
    }
  },
  "runninghub-seedance": {
    "text_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "5",
        "ratio": "adaptive",
        "generateAudio": true
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "5",
        "ratio": "adaptive",
        "generateAudio": true
      }
    }
  },
  "rh-veo-3.1": {
    "text_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "8",
        "aspectRatio": "16:9",
        "generateAudio": true
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "8",
        "aspectRatio": "16:9",
        "generateAudio": true
      }
    }
  },
  "rh-kling-3.0": {
    "text_to_video": {
      "*": {
        "duration": "5",
        "aspectRatio": "16:9",
        "sound": true
      }
    },
    "image_to_video": {
      "*": {
        "duration": "5",
        "sound": true
      }
    }
  },
  "rh-wan-2.7": {
    "text_to_video": {
      "*": {
        "resolution": "720P",
        "duration": "5",
        "aspectRatio": "16:9",
        "promptExtend": true
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720P",
        "duration": "5",
        "promptExtend": true
      }
    }
  },
  "rh-hailuo-2.3": {
    "text_to_video": {
      "*": {
        "duration": "6",
        "enablePromptExpansion": true
      }
    },
    "image_to_video": {
      "*": {
        "duration": "6",
        "enablePromptExpansion": true
      }
    }
  },
  "rh-sora-2": {
    "text_to_video": {
      "*": {
        "size": "720x1280",
        "duration": "4"
      }
    },
    "image_to_video": {
      "*": {
        "duration": "4"
      }
    }
  },
  "rh-seedream-4.5": {
    "text_to_image": {
      "*": {
        "resolution": "2k"
      }
    },
    "image_edit": {
      "*": {
        "resolution": "2k"
      }
    }
  },
  "rh-nano-banana": {
    "text_to_image": {
      "*": {
        "aspectRatio": "1:1"
      }
    },
    "image_edit": {
      "*": {
        "aspectRatio": "1:1"
      }
    }
  },
  "rh-gpt-image-2": {
    "text_to_image": {
      "*": {
        "resolution": "2k",
        "quality": "medium",
        "aspectRatio": "16:9"
      }
    },
    "image_edit": {
      "*": {
        "resolution": "2k",
        "quality": "medium",
        "aspectRatio": "16:9"
      }
    }
  },
  "rh-qwen-image-2.0": {
    "text_to_image": {
      "*": {
        "size": "1024*1024",
        "promptExtend": true
      }
    },
    "image_edit": {
      "*": {
        "size": "1024*1024"
      }
    }
  },
  "agnes-image": {
    "text_to_image": {
      "*": {
        "size": "1024x1024"
      }
    },
    "image_edit": {
      "*": {
        "size": "1024x1024"
      }
    }
  },
  "agnes-video": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 5
      }
    },
    "image_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 5
      }
    }
  }
};
