// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案身份桥接：主进程从 modelKey 认出档案（中转接入选原生报文用）；匹配实现在 archetypeIdentity.ts。
export const ARCHETYPE_IDENTIFIER_PATTERNS: Record<string, string[]> = {
  "seedance-2": [
    "bytedance/seedance-2",
    "seedance-2",
    "seedance2",
    "bytedance/seedance-2-fast",
    "seedance-2-fast",
    "seedance2fast",
    "bytedance/seedance-2-mini",
    "seedance-2-mini",
    "seedance2mini"
  ],
  "seedance-2.5": [
    "bytedance/seedance-2-5",
    "seedance-2-5",
    "seedance-2.5",
    "seedance2.5",
    "seedance25"
  ],
  "minimax-h3": [
    "minimax-h3",
    "minimax-h3/text-to-video",
    "minimax-h3/image-to-video",
    "minimax-h3/reference-to-video",
    "hailuo-3",
    "hailuo-03",
    "hailuo3"
  ],
  "minimax-h3-max": [
    "minimax/h3-max",
    "MiniMax-H3-Max"
  ],
  "minimax-music-3": [
    "minimax/music-3",
    "music-3"
  ],
  "minimax-speech-2.8": [
    "speech-2.8-hd",
    "speech-2.8-turbo"
  ],
  "eleven-v3": [
    "eleven_v3",
    "eleven-v3"
  ],
  "eleven-music-v2": [
    "music_v2",
    "eleven-music-v2"
  ],
  "eleven-sfx-v2": [
    "eleven_text_to_sound_v2",
    "eleven-sfx-v2"
  ],
  "eleven-scribe-v2": [
    "scribe_v2",
    "scribe-v2"
  ],
  "meshy-7": [
    "meshy-7",
    "meshy7"
  ],
  "runway-gen4.5": [
    "gen4.5",
    "runway-gen4.5",
    "runway-gen-4.5"
  ],
  "runway-gen4-turbo": [
    "gen4_turbo",
    "runway-gen4-turbo",
    "runway-gen-4-turbo"
  ],
  "runway-video": [
    "seedance2",
    "seedance2_fast",
    "seedance2_mini",
    "wan3",
    "grok_imagine_1_5",
    "hailuo3",
    "veo3.1",
    "veo3.1_fast",
    "happyhorse_1_0",
    "gemini_omni_flash"
  ],
  "runway-video-t2v": [
    "happyhorse_1_0"
  ],
  "runway-image-reference": [
    "gen4_image_turbo"
  ],
  "runway-image": [
    "muse_image",
    "grok_imagine_image_2",
    "seedream5_pro",
    "seedream5_lite",
    "gen4_image",
    "gen4_image_turbo",
    "gemini_image3_pro",
    "gemini_image3.1_flash",
    "gpt_image_2",
    "gemini_2.5_flash"
  ],
  "runway-audio": [
    "seed_audio",
    "eleven_text_to_sound_v2",
    "eleven_multilingual_v2",
    "eleven_v3",
    "runway-audio"
  ],
  "happyhorse": [
    "happyhorse",
    "happyhorse/text-to-video",
    "happyhorse/image-to-video",
    "happyhorse/reference-to-video",
    "happyhorse/video-edit"
  ],
  "gpt-image-2": [
    "gpt-image-2",
    "gpt-image-2-text-to-image",
    "gpt-image-2-image-to-image",
    "gpt-4o-image"
  ],
  "seedream": [
    "seedream",
    "seedream/4.5-text-to-image",
    "seedream/4.5-edit",
    "bytedance/seedream-v4-edit",
    "bytedance/seedream-v4-text-to-image",
    "seedream-4-5",
    "seedream-v4",
    "doubao-seedream-4.5"
  ],
  "kie-seedream-5-pro": [
    "seedream/5-pro-text-to-image",
    "seedream/5-pro-image-to-image"
  ],
  "kie-seedream-5-lite": [
    "seedream/5-lite-text-to-image",
    "seedream/5-lite-image-to-image"
  ],
  "nano-banana-2": [
    "nano-banana-2",
    "gemini-3.1-flash-image",
    "gemini-3.1-flash-image-preview",
    "gemini-3.1-flash-image-preview-official"
  ],
  "nano-banana-2-lite": [
    "nano-banana-2-lite"
  ],
  "nano-banana": [
    "nano-banana",
    "google/nano-banana",
    "google/nano-banana-edit",
    "nano-banana-pro",
    "gemini-2.5-flash-image-preview"
  ],
  "flux-2-pro": [
    "flux-2/pro-text-to-image",
    "flux-2/pro-image-to-image"
  ],
  "kling-3.0": [
    "kling-3.0",
    "kling-3.0/video",
    "kling-3",
    "kling3",
    "kling-v3"
  ],
  "qwen-image-3": [
    "qwen-image-3.0",
    "qwen-image-3-0",
    "qwen-image-3.0-pro",
    "qwen-image-3-0-pro"
  ],
  "qwen-image": [
    "qwen-image",
    "qwen-image-2.0",
    "qwen-image-2-0",
    "qwen-image-2.0-pro",
    "qwen-image-2-0-pro"
  ],
  "imagen-4": [
    "imagen-4",
    "imagen-4.0-apimart",
    "imagen-4-0-apimart"
  ],
  "z-image-turbo": [
    "z-image-turbo",
    "z-image"
  ],
  "sora-2": [
    "sora-2",
    "sora-2-pro",
    "sora2"
  ],
  "veo-3.1": [
    "veo-3.1",
    "veo3.1",
    "veo3.1-fast",
    "veo3.1-quality",
    "veo3.1-lite"
  ],
  "wan-2.7": [
    "wan-2.7",
    "wan2.7",
    "wan-2-7",
    "wan2.7-r2v",
    "wan-2-7-r2v"
  ],
  "wan-3.0": [
    "wan/3-0-video",
    "wan/3-0-video-prime",
    "wan-3.0",
    "wan3.0"
  ],
  "wan-3.0-apimart": [
    "wan3.0-video",
    "wan3-0-video"
  ],
  "hailuo-2.3": [
    "hailuo-2.3",
    "minimax-hailuo-2.3",
    "hailuo-2-3",
    "minimax-hailuo-2.3-fast",
    "MiniMax-Hailuo-2.3",
    "MiniMax-Hailuo-2.3-Fast"
  ],
  "grok-imagine-1.5-video": [
    "grok-imagine-1.5-video-apimart",
    "grok-imagine-1.5-video-ext",
    "grok-imagine-1.5-video",
    "grok-imagine-1.5"
  ],
  "gemini-omni-1.1": [
    "google/gemini-omni-flash-1-1",
    "gemini-omni-flash-1-1"
  ],
  "seedance-2-apimart": [
    "doubao-seedance-2.0",
    "doubao-seedance-2-0",
    "doubao-seedance-2.0-fast",
    "doubao-seedance-2-0-fast",
    "doubao-seedance-2.0-face",
    "doubao-seedance-2-0-face",
    "doubao-seedance-2.0-fast-face",
    "doubao-seedance-2-0-fast-face",
    "doubao-seedance-2.0-mini",
    "doubao-seedance-2-0-mini"
  ],
  "seedance-2.5-apimart": [
    "doubao-seedance-2.5",
    "doubao-seedance-2-5"
  ],
  "minimax-h3-apimart": [
    "MiniMax-H3"
  ],
  "minimax-h3-regeneration": [
    "MiniMax-H3-Regeneration"
  ],
  "vidu-q3": [
    "viduq3",
    "viduq3-mix",
    "vidu-q3"
  ],
  "kling-3.0-turbo": [
    "kling-3.0-turbo",
    "kling-3-0-turbo",
    "kling3.0-turbo"
  ],
  "happyhorse-1.1": [
    "happyhorse-1.1",
    "happyhorse-1-1"
  ],
  "seedream-5-pro": [
    "doubao-seedream-5-0-pro",
    "seedream-5-0-pro",
    "seedream-5.0-pro"
  ],
  "omni-flash-ext": [
    "omni-flash-ext"
  ],
  "nomi-audio": [
    "nomi-audio"
  ],
  "suno-v5.5": [
    "suno-v5.5",
    "suno-v5-5"
  ],
  "suno-sfx-v5.5": [
    "suno-sounds-v5.5",
    "suno-sounds-v5-5"
  ],
  "lyria-3.5": [
    "flowmusic-lyria-3.5"
  ],
  "volcengine-doubao-tts": [
    "doubao-seed-tts-2.0",
    "doubao-tts-2.0"
  ],
  "seed-tts": [
    "seed-tts-2.0",
    "seed-tts"
  ],
  "modelscope-image": [
    "tongyi-mai/z-image",
    "qwen/qwen-image-2",
    "black-forest-labs/flux",
    "modelscope",
    "Tongyi-MAI/Z-Image-Turbo",
    "Tongyi-MAI/Z-Image",
    "Qwen/Qwen-Image-2512",
    "black-forest-labs/FLUX.2-klein-9B",
    "black-forest-labs/FLUX.1-Krea-dev",
    "MAILAND/majicflus_v1"
  ],
  "modelscope-image-edit": [
    "qwen/qwen-image-edit",
    "modelscope-edit",
    "Qwen/Qwen-Image-Edit-2511"
  ],
  "volcengine-seedream": [
    "doubao-seedream-5-0-260128",
    "doubao-seedream-4-5-251128",
    "doubao-seedream-4-0-250828"
  ],
  "volcengine-seedream-5-pro": [
    "doubao-seedream-5-0-pro-260628"
  ],
  "volcengine-seedance-2": [
    "doubao-seedance-2-0-260128",
    "doubao-seedance-2-0-fast-260128",
    "doubao-seedance-2-0-mini-260615"
  ],
  "volcengine-seedance-2-5": [
    "doubao-seedance-2-5-260628"
  ],
  "dreamina-seedance-2": [
    "dreamina-seedance-2.0",
    "dreamina-seedance",
    "seedance2.0fast",
    "seedance2.0",
    "seedance2.0_vip",
    "seedance2.0fast_vip",
    "seedance2.0mini",
    "seedance2.5"
  ],
  "dreamina-image": [
    "dreamina-image",
    "5.0Pro",
    "5.0",
    "4.7",
    "4.6",
    "4.5",
    "4.1",
    "4.0",
    "3.1",
    "3.0"
  ],
  "dreamina-upscale": [
    "dreamina-upscale"
  ],
  "dreamina-multiframe": [
    "dreamina-multiframe"
  ],
  "codex-imagegen": [
    "codex-imagegen"
  ],
  "antigravity-image": [
    "antigravity-cli/generate_image"
  ],
  "hunyuan3d": [
    "hunyuan3d-v3.1",
    "hunyuan3d",
    "hunyuan-3d"
  ],
  "hitem3d": [
    "hitem3d-v21",
    "hitem3d",
    "hitem-3d"
  ],
  "meshy6": [
    "meshy6",
    "meshy-6",
    "meshy"
  ],
  "runninghub-seedance": [
    "bytedance/seedance-2.0-global",
    "seedance-2.0-global"
  ],
  "rh-veo-3.1": [
    "rhart-video-v3.1-pro-official",
    "veo3.1-rh"
  ],
  "rh-kling-3.0": [
    "kling-v3.0-pro",
    "kling-v3.0-rh"
  ],
  "rh-wan-2.7": [
    "rh-wan-2.7"
  ],
  "rh-hailuo-2.3": [
    "rh-hailuo-2.3"
  ],
  "rh-sora-2": [
    "rhart-video-s-official",
    "sora-2-rh"
  ],
  "rh-seedream-4.5": [
    "seedream-v4.5",
    "seedream-4.5-rh"
  ],
  "rh-nano-banana": [
    "rhart-image-v1",
    "nano-banana-rh"
  ],
  "rh-gpt-image-2": [
    "rhart-image-g-2-official",
    "gpt-image-2-rh"
  ],
  "rh-qwen-image-2.0": [
    "rh-qwen-image-2.0"
  ],
  "agnes-image": [
    "agnes-image",
    "agnes-image-2.0-flash"
  ],
  "agnes-image-2.1": [
    "agnes-image-2.1-flash"
  ],
  "agnes-video": [
    "agnes-video",
    "agnes-video-v2.0",
    "agnes-video-v2"
  ],
  "agnes-video-2.5": [
    "agnes-video-2.5"
  ],
  "agnes-video-2.5-flash": [
    "agnes-video-2.5-flash"
  ]
};
