// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案参数默认值桥接（video 分片）。合并出口在 archetypeWireDefaults.generated.ts。
export const ARCHETYPE_WIRE_DEFAULTS_VIDEO: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  "seedance-2": {
    "text_to_video": {
      "*": {
        "resolution": "720p",
        "aspect_ratio": "16:9",
        "duration": 5,
        "generate_audio": true,
        "model": "bytedance/seedance-2"
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "aspect_ratio": "16:9",
        "duration": 5,
        "generate_audio": true,
        "model": "bytedance/seedance-2"
      }
    }
  },
  "seedance-2.5": {
    "text_to_video": {
      "*": {
        "resolution": "720p",
        "aspect_ratio": "adaptive",
        "duration": 5,
        "generate_audio": true,
        "return_last_frame": false
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "aspect_ratio": "adaptive",
        "duration": 5,
        "generate_audio": true,
        "return_last_frame": false
      }
    }
  },
  "minimax-h3": {
    "text_to_video": {
      "*": {
        "resolution": "2K",
        "aspect_ratio": "adaptive",
        "duration": 6,
        "model": "minimax-h3/reference-to-video"
      }
    }
  },
  "minimax-h3-max": {
    "text_to_video": {
      "*": {
        "resolution": "768P",
        "duration": 5,
        "aspect_ratio": "16:9"
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "768P",
        "duration": 5
      }
    }
  },
  "runway-gen4.5": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "1280:720",
        "duration": 5,
        "seed": 0
      }
    },
    "image_to_video": {
      "*": {
        "aspect_ratio": "1280:720",
        "duration": 5,
        "seed": 0
      }
    }
  },
  "runway-gen4-turbo": {
    "image_to_video": {
      "*": {
        "aspect_ratio": "1280:720",
        "duration": 5,
        "seed": 0
      }
    }
  },
  "runway-video": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "1280:720",
        "duration": 5,
        "generate_audio": true
      }
    },
    "image_to_video": {
      "*": {
        "aspect_ratio": "1280:720",
        "duration": 5,
        "generate_audio": true
      }
    }
  },
  "runway-video-t2v": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "1280:720",
        "duration": 5,
        "generate_audio": true
      }
    }
  },
  "happyhorse": {
    "text_to_video": {
      "*": {
        "resolution": "1080p",
        "audio_setting": "auto",
        "model": "happyhorse/video-edit"
      }
    }
  },
  "kling-3.0": {
    "text_to_video": {
      "*": {
        "mode": "pro",
        "duration": "5",
        "aspect_ratio": "16:9",
        "sound": false,
        "model": "kling-3.0/video"
      },
      "apimart": {
        "mode": "pro",
        "duration": 5,
        "aspect_ratio": "16:9",
        "audio": false,
        "model": "kling-3.0/video"
      }
    },
    "image_to_video": {
      "*": {
        "mode": "pro",
        "duration": "5",
        "aspect_ratio": "16:9",
        "sound": false,
        "model": "kling-3.0/video"
      },
      "apimart": {
        "mode": "pro",
        "duration": 5,
        "aspect_ratio": "16:9",
        "audio": false,
        "model": "kling-3.0/video"
      }
    }
  },
  "sora-2": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 4,
        "model": "sora-2"
      }
    },
    "image_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 4,
        "model": "sora-2"
      }
    }
  },
  "veo-3.1": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "model": "veo3.1-fast"
      }
    },
    "image_to_video": {
      "*": {
        "generation_type": "frame",
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "model": "veo3.1-fast"
      }
    }
  },
  "wan-2.7": {
    "text_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "1080P",
        "duration": 5,
        "model": "wan2.7"
      }
    },
    "image_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "1080P",
        "duration": 5,
        "model": "wan2.7-r2v"
      }
    }
  },
  "wan-3.0": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "adaptive",
        "resolution": "1080P",
        "duration": 5,
        "audio": true,
        "model": "wan/3-0-video"
      }
    },
    "image_to_video": {
      "*": {
        "aspect_ratio": "adaptive",
        "resolution": "1080P",
        "duration": 5,
        "audio": true,
        "model": "wan/3-0-video"
      }
    }
  },
  "wan-3.0-apimart": {
    "text_to_video": {
      "*": {
        "size": "adaptive",
        "resolution": "1080P",
        "duration": 5,
        "audio": true,
        "watermark": false
      }
    },
    "image_to_video": {
      "*": {
        "generation_type": "reference",
        "size": "adaptive",
        "resolution": "1080P",
        "duration": 5,
        "audio": true,
        "watermark": false
      }
    }
  },
  "hailuo-2.3": {
    "text_to_video": {
      "*": {
        "resolution": "768p",
        "duration": 6,
        "model": "MiniMax-Hailuo-2.3"
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "768p",
        "duration": 6,
        "model": "MiniMax-Hailuo-2.3"
      }
    }
  },
  "grok-imagine-1.5-video": {
    "text_to_video": {
      "*": {
        "size": "16:9",
        "quality": "480p",
        "duration": 6
      }
    },
    "image_to_video": {
      "*": {
        "quality": "480p",
        "duration": 6
      }
    }
  },
  "gemini-omni-1.1": {
    "text_to_video": {
      "*": {
        "duration": 8,
        "aspect_ratio": "16:9",
        "resolution": "720p"
      }
    },
    "image_to_video": {
      "*": {
        "duration": 8,
        "aspect_ratio": "16:9",
        "resolution": "720p"
      }
    }
  },
  "seedance-2-apimart": {
    "text_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2.0-fast"
      }
    },
    "image_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2.0-fast"
      }
    }
  },
  "seedance-2.5-apimart": {
    "text_to_video": {
      "*": {
        "size": "adaptive",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "return_last_frame": false
      }
    },
    "image_to_video": {
      "*": {
        "size": "adaptive",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "return_last_frame": false
      }
    }
  },
  "minimax-h3-apimart": {
    "text_to_video": {
      "*": {
        "resolution": "2K",
        "aspect_ratio": "16:9",
        "duration": 5,
        "watermark": false
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "2K",
        "aspect_ratio": "adaptive",
        "duration": 5,
        "watermark": false
      }
    }
  },
  "vidu-q3": {
    "image_to_video": {
      "*": {
        "duration": 5,
        "resolution": "720p",
        "aspect_ratio": "16:9",
        "model": "viduq3"
      }
    }
  },
  "kling-3.0-turbo": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 5
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "duration": 5
      }
    }
  },
  "happyhorse-1.1": {
    "text_to_video": {
      "*": {
        "resolution": "1080P",
        "size": "16:9",
        "duration": 5
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "1080P",
        "size": "16:9",
        "duration": 5
      }
    }
  },
  "omni-flash-ext": {
    "text_to_video": {
      "*": {
        "size": "16:9",
        "resolution": "720p",
        "duration": 6
      }
    },
    "image_to_video": {
      "*": {
        "generation_type": "reference",
        "size": "16:9",
        "resolution": "720p",
        "duration": 6
      }
    }
  },
  "volcengine-seedance-2": {
    "text_to_video": {
      "*": {
        "ratio": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2-0-260128"
      }
    },
    "image_to_video": {
      "*": {
        "ratio": "16:9",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "model": "doubao-seedance-2-0-260128"
      }
    }
  },
  "volcengine-seedance-2-5": {
    "text_to_video": {
      "*": {
        "ratio": "adaptive",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "output_format": "mp4"
      }
    },
    "image_to_video": {
      "*": {
        "ratio": "adaptive",
        "resolution": "720p",
        "duration": 5,
        "generate_audio": true,
        "output_format": "mp4"
      }
    }
  },
  "dreamina-seedance-2": {
    "text_to_video": {
      "*": {
        "dreamina_cmd": "text2video",
        "ratio": "16:9",
        "video_resolution": "720p",
        "duration": 5,
        "model": "seedance2.0fast"
      }
    },
    "image_to_video": {
      "*": {
        "dreamina_cmd": "multimodal2video",
        "ratio": "16:9",
        "video_resolution": "720p",
        "duration": 5,
        "model": "seedance2.0fast"
      }
    }
  },
  "dreamina-multiframe": {
    "image_to_video": {
      "*": {
        "video_resolution": "720p",
        "duration": 3
      }
    }
  },
  "runninghub-seedance": {
    "text_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "5",
        "ratio": "adaptive",
        "generateAudio": true
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "5",
        "ratio": "adaptive",
        "generateAudio": true
      }
    }
  },
  "rh-veo-3.1": {
    "text_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "8",
        "aspectRatio": "16:9",
        "generateAudio": true
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720p",
        "duration": "8",
        "aspectRatio": "16:9",
        "generateAudio": true
      }
    }
  },
  "rh-kling-3.0": {
    "text_to_video": {
      "*": {
        "duration": "5",
        "aspectRatio": "16:9",
        "sound": true
      }
    },
    "image_to_video": {
      "*": {
        "duration": "5",
        "sound": true
      }
    }
  },
  "rh-wan-2.7": {
    "text_to_video": {
      "*": {
        "resolution": "720P",
        "duration": "5",
        "aspectRatio": "16:9",
        "promptExtend": true
      }
    },
    "image_to_video": {
      "*": {
        "resolution": "720P",
        "duration": "5",
        "promptExtend": true
      }
    }
  },
  "rh-hailuo-2.3": {
    "text_to_video": {
      "*": {
        "duration": "6",
        "enablePromptExpansion": true
      }
    },
    "image_to_video": {
      "*": {
        "duration": "6",
        "enablePromptExpansion": true
      }
    }
  },
  "rh-sora-2": {
    "text_to_video": {
      "*": {
        "size": "720x1280",
        "duration": "4"
      }
    },
    "image_to_video": {
      "*": {
        "duration": "4"
      }
    }
  },
  "agnes-video": {
    "text_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 5,
        "frame_rate": 24
      }
    },
    "image_to_video": {
      "*": {
        "aspect_ratio": "16:9",
        "resolution": "720p",
        "duration": 5,
        "frame_rate": 24
      }
    }
  },
  "agnes-video-2.5": {
    "text_to_video": {
      "*": {
        "duration": "5",
        "size": "720P",
        "aspect_ratio": "16:9"
      }
    },
    "image_to_video": {
      "*": {
        "duration": "5",
        "size": "720P",
        "aspect_ratio": "16:9"
      }
    }
  },
  "agnes-video-2.5-flash": {
    "text_to_video": {
      "*": {
        "duration": "5",
        "size": "720P",
        "aspect_ratio": "16:9"
      }
    },
    "image_to_video": {
      "*": {
        "duration": "5",
        "size": "720P",
        "aspect_ratio": "16:9"
      }
    }
  }
};
